---
- name: Upgrade all yum packages
  yum:
    name: "*"
    state: latest
- name: Install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - curl
      - pip3
      - build-essential
      - software-properties-common
      - curl

- name: be sure ntp is installed
  yum:
    name: ntp
    state: present
  tags: ntp

- name: be sure ntp is configured
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

- name: Add repository
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    gpgcheck: no

    #Install docker using package module
- name: Install docker
  package:
    name: docker-ce-18.09.1-3.el7.x86_64
    state: present
    #Enable docekr service
- name: enable Docker services
  service:
    name: "docker"
    state: started
    enabled: yes

    #Install docker module to use docker command
- name: Installing Docker SDK for python3
  command:
    pip3 install docker
    #Launch apache server and expose to port 80 and mount volume
- name: launching apache server in docker
  docker_container:
    name: webserver
    image: httpd
    state: started
