---
# Provision instances in AWS specific to the LAMP HA Proxy demo
- name: Launch webserver instances
  ec2:
    access_key: "{{ ec2_access_key }}"
    secret_key: "{{ ec2_secret_key }}"
    keypair: "{{ ec2_keypair }}"
    group: "{{ ec2_security_group }}"
    type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    instance_tags: "{'ansible_group':'webservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
    count: "{{ ec2_instance_count }}"
    wait: true
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"

- name: Add the newly created EC2 instance(s) to the local host group
  local_action: lineinfile
    path="hosts"
    regexp={{ item.public_ip }}
    insertafter="[ec2]" line="{{ item.public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=keys/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
  with_items: "{{ ec2.instances }}"
